import type { BuildingDefinition } from "../entities/Building";

export const BuildingCategory = {
  LIVING: "living",
  PRODUCTION: "production",
  STORAGE: "storage",
  INFRASTRUCTURE: "infrastructure",
  DEFENSE: "defense",
} as const;

export type BuildingCategory = typeof BuildingCategory[keyof typeof BuildingCategory];


export const BUILDING_SEED: BuildingDefinition[] = [
  // LIVING
  {
    id: "hab",
    name: "Centrum Kolonii",
    category: BuildingCategory.LIVING,
    color: "#93c5fd",
    cost: { power: 5, water: 1 },
    production: { o2: 0.15, power: -0.10, water: -0.05 },
    modelPath: "/models/mars/rocket_baseA.glb",
    modelScale: 2.5,
    colonistCapacity: 10,
    upgrades: [
      {
        level: 2,
        cost: { power: 6, water: 3 },
        productionMultiplier: 1.5,
        description: "+10 Miejsc dla Kolonistów (Razem 20)",
      },
      {
        level: 3,
        cost: { power: 12, water: 6, biomass: 4 },
        productionMultiplier: 2.0,
        description: "+15 Miejsc dla Kolonistów (Razem 35)",
      },
    ],
  },
  {
    id: "greenhouse",
    name: "Szklarnia Bio",
    category: BuildingCategory.LIVING,
    color: "#86efac",
    cost: { power: 3, water: 4 },
    production: { o2: 0.30, biomass: 0.20, power: -0.10, water: -0.15 },
    modelPath: "/models/mars/hangar_roundGlass.glb",
    modelScale: 2.5,
    dependsOn: ["hab"],
    requiredTech: "advanced_hab",
    connectionType: "water" as const,
    bonusNeighbors: [
      { neighborId: "o2-gen", bonusPercent: 20, description: "+20% O₂ obok Generatora" },
      { neighborId: "ice",    bonusPercent: 15, description: "+15% Bio obok Ekstraktora" },
    ],
    influenceRadius: 4,
    upgrades: [
      {
        level: 2,
        cost: { power: 4, water: 4 },
        productionMultiplier: 1.5,
        description: "+50% Produkcji",
      },
      {
        level: 3,
        cost: { power: 8, water: 6, biomass: 3 },
        productionMultiplier: 2.2,
        description: "+120% Produkcji",
      },
    ],
  },

  // PRODUCTION
  {
    id: "o2-gen",
    name: "Generator Tlenu",
    category: BuildingCategory.PRODUCTION,
    color: "#67e8f9",
    cost: { power: 4, water: 2 },
    production: { o2: 0.60, power: -0.15 },
    modelPath: "/models/mars/machine_generator.glb",
    modelScale: 2.5,
    dependsOn: ["hab"],
    requiredTech: "o2_synthesis",
    connectionType: "power" as const,
    influenceRadius: 3,
    upgrades: [
      {
        level: 2,
        cost: { power: 5, water: 3 },
        productionMultiplier: 1.5,
        description: "+50% Produkcji O₂",
      },
      {
        level: 3,
        cost: { power: 8, water: 5 },
        productionMultiplier: 2.2,
        description: "+120% Produkcji O₂",
      },
    ],
  },
  {
    id: "solar",
    name: "Generator Solarny",
    category: BuildingCategory.PRODUCTION,
    color: "#fde68a",
    cost: { biomass: 0.5 },
    production: { power: 0.50 },
    tags: ["dayScaled"],
    modelPath: "/models/mars/machine_generator.glb",
    modelScale: 3.0,
    connectionType: "power" as const,
    bonusNeighbors: [
      { neighborId: "battery", bonusPercent: 15, description: "+15% Power obok Stacji" },
    ],
    influenceRadius: 2,
    upgrades: [
      {
        level: 2,
        cost: { biomass: 1.5, power: 2 },
        productionMultiplier: 1.5,
        description: "+50% Energii",
      },
      {
        level: 3,
        cost: { biomass: 3, water: 2 },
        productionMultiplier: 2.2,
        description: "+120% Energii",
      },
    ],
  },
  {
    id: "rtg",
    name: "Blok RTG",
    category: BuildingCategory.PRODUCTION,
    color: "#f472b6",
    cost: { biomass: 5, water: 2 },
    production: { power: 0.60 },
    modelPath: "/models/mars/machine_generatorLarge.glb",
    modelScale: 3.0,
    dependsOn: ["solar"],
    requiredTech: "nuclear_power",
    influenceRadius: 2.5,
    upgrades: [
      {
        level: 2,
        cost: { biomass: 6, water: 3 },
        productionMultiplier: 1.5,
        description: "+50% Energii",
      },
      {
        level: 3,
        cost: { biomass: 10, water: 5 },
        productionMultiplier: 2.2,
        description: "+120% Energii",
      },
    ],
  },
  {
    id: "ice",
    name: "Ekstraktor Lodu",
    category: BuildingCategory.PRODUCTION,
    color: "#a5f3fc",
    cost: { power: 4 },
    production: { water: 0.40, power: -0.20 },
    modelPath: "/models/mars/pipe_entrance.glb",
    modelScale: 2.5,
    dependsOn: ["hab"],
    extractsDeposit: "ice",
    influenceRadius: 3,
    upgrades: [
      {
        level: 2,
        cost: { power: 4, biomass: 2 },
        productionMultiplier: 1.5,
        extractionRadius: 2,
        unlockedUnit: "rover",
        description: "Łazik Logistyczny (R=2, x1.5)",
      },
      {
        level: 3,
        cost: { power: 8, biomass: 4 },
        productionMultiplier: 2.2,
        extractionRadius: 4,
        unlockedUnit: "drone",
        description: "Dron Powietrzny (R=4, x2.2)",
      },
    ],
  },
  {
    id: "miner",
    name: "Kopalnia",
    category: BuildingCategory.PRODUCTION,
    color: "#94a3b8",
    cost: { power: 6, water: 2 },
    production: { biomass: 0.40, power: -0.30 },
    modelPath: "/models/mars/craft_miner.glb",
    modelScale: 3.0,
    dependsOn: ["ice"],
    requiredTech: "deep_mining",
    extractsDeposit: "minerals",
    connectionType: "biomass" as const,
    bonusNeighbors: [
      { neighborId: "silo",  bonusPercent: 10, description: "+10% Biomasa obok Silosu" },
    ],
    influenceRadius: 3.5,
    upgrades: [
      {
        level: 2,
        cost: { power: 6, water: 2, biomass: 2 },
        productionMultiplier: 1.5,
        extractionRadius: 2,
        unlockedUnit: "rover",
        description: "Łazik Logistyczny (R=2, x1.5)",
      },
      {
        level: 3,
        cost: { power: 10, water: 4, biomass: 4 },
        productionMultiplier: 2.2,
        extractionRadius: 4,
        unlockedUnit: "drone",
        description: "Dron Powietrzny (R=4, x2.2)",
      },
    ],
  },

  // STORAGE
  {
    id: "battery",
    name: "Stacja Przekaźnikowa",
    category: BuildingCategory.STORAGE,
    color: "#fbbf24",
    cost: { biomass: 1, water: 1 },
    capacity: { power: 50 },
    modelPath: "/models/mars/machine_wireless.glb",
    modelScale: 2.5,
    dependsOn: ["solar"],
    requiredTech: "solar_array",
    influenceRadius: 2,
  },
  {
    id: "watertank",
    name: "Zbiornik H2O",
    category: BuildingCategory.STORAGE,
    color: "#60a5fa",
    cost: { power: 2, biomass: 0.5 },
    capacity: { water: 50 },
    modelPath: "/models/mars/machine_barrel.glb",
    modelScale: 2.5,
    dependsOn: ["ice"],
    requiredTech: "deep_mining",
    influenceRadius: 2.5,
  },
  {
    id: "silo",
    name: "Silos Materiałowy",
    category: BuildingCategory.STORAGE,
    color: "#a3e635",
    cost: { power: 2, water: 1 },
    capacity: { biomass: 40 },
    modelPath: "/models/mars/machine_barrelLarge.glb",
    modelScale: 2.5,
    dependsOn: ["miner"],
    requiredTech: "deep_mining",
    influenceRadius: 2.5,
  },

  // INFRASTRUCTURE
  {
    id: "lab",
    name: "Laboratorium",
    category: BuildingCategory.INFRASTRUCTURE,
    color: "#d8b4fe",
    cost: { power: 10, biomass: 5 },
    production: { power: -0.40, water: -0.20, biomass: 0.10 },
    modelPath: "/models/mars/machine_wireless.glb",
    modelScale: 2.5,
    dependsOn: ["hab"],
    requiredTech: "basic_structures",
    connectionType: "data" as const,
    bonusNeighbors: [
      { neighborId: "hab",  bonusPercent: 25, description: "+25% Biomasa obok Kolonii" },
    ],
    influenceRadius: 3.5,
    upgrades: [
      {
        level: 2,
        cost: { power: 12, biomass: 6 },
        productionMultiplier: 1.5,
        description: "+50% Badań",
      },
      {
        level: 3,
        cost: { power: 20, biomass: 10 },
        productionMultiplier: 2.2,
        description: "+120% Badań",
      },
    ],
  },

  // DEFENSE
  {
    id: "turret",
    name: "Wieżyczka",
    category: BuildingCategory.DEFENSE,
    color: "#ef4444",
    cost: { power: 10, biomass: 2 },
    production: { power: -0.05 },
    modelPath: "/models/mars/turret_single.glb",
    modelScale: 3.0,
    dependsOn: ["hab", "solar"],
    requiredTech: "perimeter_defense",
    influenceRadius: 4,
  },

  // MEGASTRUCTURES
  {
    id: "biosphere_dome",
    name: "Kopuła Biosfery",
    category: BuildingCategory.LIVING,
    color: "#34d399",
    cost: { biomass: 200, water: 100 },
    production: { o2: 2.0, biomass: 1.5, power: -20 },
    colonistCapacity: 50,
    modelPath: "/models/mars/hangar_roundGlass.glb",
    modelScale: 3.8,
    dependsOn: ["greenhouse"],
    requiredTech: "biodome",
    connectionType: "water" as const,
    influenceRadius: 5.0,
    upgrades: [
      {
        level: 2,
        cost: { biomass: 150, water: 80, power: 30 },
        productionMultiplier: 1.5,
        description: "+25 Miejsc dla Kolonistów i +50% Produkcji",
      },
      {
        level: 3,
        cost: { biomass: 300, water: 150, power: 60 },
        productionMultiplier: 2.0,
        description: "+50 Miejsc dla Kolonistów i +100% Produkcji",
      },
    ],
  },
  {
    id: "atmosphere_factory",
    name: "Fabryka Atmosfery",
    category: BuildingCategory.PRODUCTION,
    color: "#fb923c",
    cost: { biomass: 300, power: 50 },
    production: { biomass: -0.2, power: -5, o2: 1.2 },
    modelPath: "/models/mars/rocket_baseA.glb",
    modelScale: 3.2,
    dependsOn: ["o2-gen"],
    requiredTech: "atmosphere_terraforming",
    connectionType: "power" as const,
    influenceRadius: 4.5,
    upgrades: [
      {
        level: 2,
        cost: { biomass: 200, power: 40 },
        productionMultiplier: 1.6,
        description: "+60% Emisji i Produkcji O₂",
      },
      {
        level: 3,
        cost: { biomass: 400, power: 80 },
        productionMultiplier: 2.3,
        description: "+130% Emisji i Produkcji O₂",
      },
    ],
  },
  {
    id: "fusion_reactor",
    name: "Reaktor Fuzyjny",
    category: BuildingCategory.PRODUCTION,
    color: "#38bdf8",
    cost: { biomass: 400 },
    production: { power: 150, water: -0.1 },
    modelPath: "/models/mars/machine_generatorLarge.glb",
    modelScale: 3.5,
    dependsOn: ["rtg"],
    requiredTech: "fusion_power",
    connectionType: "power" as const,
    influenceRadius: 4.0,
    upgrades: [
      {
        level: 2,
        cost: { biomass: 250, water: 50 },
        productionMultiplier: 1.5,
        description: "+50% Mocy (+225 kW)",
      },
      {
        level: 3,
        cost: { biomass: 500, water: 100 },
        productionMultiplier: 2.2,
        description: "+120% Mocy (+330 kW)",
      },
    ],
  },
];

export const BUILDING_DEFINITIONS: Record<string, BuildingDefinition> =
  Object.fromEntries(BUILDING_SEED.map(d => [d.id, d]));
