import type { Scenario } from '../entities/Scenario';

export const SCENARIOS: Scenario[] = [
  {
    id: 'scenario_gale_crater',
    title: 'Gale Crater Outpost',
    description: 'Stabilna strefa lądowania w Kraterze Gale. Zbalansowane zasoby naturalne, umiarkowany klimat i bezpieczne otoczenie – idealne warunki na założenie pierwszej samowystarczalnej placówki.',
    difficulty: 'easy',
    seed: 1042,
    terrainArchetype: 'plains',
    mapRadius: 20,
    startingResources: {
      o2: 12,
      power: 12,
      water: 8,
      biomass: 4,
      minerals: 60,
    },
    startingCapacity: {
      power: 15,
      water: 15,
      biomass: 15,
      minerals: 200,
    },
    customPOIs: [
      {
        model: 'poi_abandoned_lab',
        count: 1,
        terrainPreference: ['highland', 'plains'],
      },
    ],
    modifiers: {
      stormFrequency: 0.7,
      alienAggression: 0,
      solarEfficiency: 1.0,
      initialAlienWave: 0,
    },
    tags: ['Tutorial', 'Standard', 'Zbalansowany'],
    objectives: [
      'Ustabilizuj produkcję energii i tlenu',
      'Zbadaj opuszczone laboratorium badawcze',
      'Osiągnij samowystarczalność bazy',
    ],
    icon: '🪐',
    defaultColonyName: 'Gale Pioneer Station',
  },
  {
    id: 'scenario_olympus_rescue',
    title: 'Olympus Mons Survival',
    description: 'Szorstkie zbocza i podnóża Olympus Mons. Poprzednia ekspedycja badawcza uległa katastrofie. Zmagaj się ze skrajnymi burzami pyłowymi i deficytem wody, odbudowując kolonię z ruin.',
    difficulty: 'hard',
    seed: 8820,
    terrainArchetype: 'mountains',
    mapRadius: 22,
    startingResources: {
      o2: 4,
      power: 6,
      water: 2,
      biomass: 0,
      minerals: 40,
    },
    startingCapacity: {
      power: 10,
      water: 10,
      biomass: 10,
      minerals: 150,
    },
    customPOIs: [
      {
        model: 'poi_abandoned_lab',
        count: 2,
        terrainPreference: ['highland', 'rocky'],
      },
      {
        model: 'poi_crashed_freighter',
        count: 1,
        terrainPreference: ['rocky', 'plains'],
      },
    ],
    modifiers: {
      stormFrequency: 2.0,
      alienAggression: 0.5,
      solarEfficiency: 0.8,
      initialAlienWave: 0,
    },
    tags: ['Survival', 'Ruiny', 'Górski'],
    objectives: [
      'Przetrwaj gwałtowne burze pyłowe',
      'Zlokalizuj ruiny dawnych laboratoriów',
      'Zabezpiecz krytyczne źródła lodu w górskich przełęczach',
    ],
    icon: '🏔️',
    defaultColonyName: 'Olympus Haven Alpha',
  },
  {
    id: 'scenario_alien_infestation',
    title: 'Cydonia Alien Infestation',
    description: 'Geotermalna kaldera opanowana przez agresywne formy życia i gniazda obcych. Priorytetem jest wzniesienie wieżyczek obronnych, zabezpieczenie perymetru i odparcie fal inwazji.',
    difficulty: 'hard',
    seed: 6667,
    terrainArchetype: 'volcanic_caldera',
    mapRadius: 22,
    startingResources: {
      o2: 8,
      power: 16,
      water: 6,
      biomass: 2,
      minerals: 80,
    },
    startingCapacity: {
      power: 20,
      water: 15,
      biomass: 10,
      minerals: 200,
    },
    customPOIs: [
      {
        model: 'poi_alien_hive',
        count: 3,
        terrainPreference: ['deep_crater', 'lowland'],
      },
      {
        model: 'poi_abandoned_lab',
        count: 1,
        terrainPreference: ['highland', 'plains'],
      },
    ],
    modifiers: {
      stormFrequency: 1.0,
      alienAggression: 2.5,
      solarEfficiency: 0.9,
      initialAlienWave: 1,
    },
    tags: ['Obrona', 'Obcy', 'Walka'],
    objectives: [
      'Postaw perymetr obronny i wieżyczki',
      'Przetrwaj fale ataków ksenomorfów',
      'Zneutralizuj strefy gniazd obcych w kraterach',
    ],
    icon: '👾',
    defaultColonyName: 'Fortress Caldera',
  },
  {
    id: 'scenario_cydonia_plains',
    title: 'Cydonia Logistics & Economy',
    description: 'Rozległe równiny Cydonia Mensae z bogatymi złożami minerałów i rozbitym gigantycznym transportowcem orbitalnym. Zbuduj rozbudowaną sieć logistyczną i potęgę przemysłową.',
    difficulty: 'normal',
    seed: 31415,
    terrainArchetype: 'plains',
    mapRadius: 24,
    startingResources: {
      o2: 8,
      power: 10,
      water: 6,
      biomass: 3,
      minerals: 100,
    },
    startingCapacity: {
      power: 15,
      water: 15,
      biomass: 15,
      minerals: 300,
    },
    customPOIs: [
      {
        model: 'poi_crashed_freighter',
        count: 2,
        terrainPreference: ['lowland', 'plains'],
      },
      {
        model: 'poi_abandoned_lab',
        count: 1,
        terrainPreference: ['plains', 'highland'],
      },
    ],
    modifiers: {
      stormFrequency: 1.1,
      alienAggression: 0.4,
      solarEfficiency: 1.15,
      initialAlienWave: 0,
    },
    tags: ['Ekonomia', 'Logistyka', 'Wrak'],
    objectives: [
      'Odzyskaj cenne moduły z wraku frachtowca',
      'Rozbuduj sieć kopalni i wydobycia minerałów',
      'Zbuduj zautomatyzowane węzły logistyczne',
    ],
    icon: '🚀',
    defaultColonyName: 'Cydonia Nexus Colony',
  },
  {
    id: 'scenario_valles_marineris',
    title: 'Valles Marineris Oceanogenesis',
    description: 'Wielki kanion Valles Marineris z gigantycznymi depozytami lodu podpowierzchniowego. Zainicjuj proces topnienia i stwórz pierwsze marsjańskie morze w głębokim rowie tektonicznym.',
    difficulty: 'normal',
    seed: 7719,
    terrainArchetype: 'canyon_valley',
    mapRadius: 24,
    startingResources: {
      o2: 8,
      power: 8,
      water: 16,
      biomass: 6,
      minerals: 60,
    },
    startingCapacity: {
      power: 20,
      water: 25,
      biomass: 20,
      minerals: 200,
    },
    customPOIs: [
      {
        model: 'poi_abandoned_lab',
        count: 1,
        terrainPreference: ['highland', 'rocky'],
      },
      {
        model: 'poi_crashed_freighter',
        count: 1,
        terrainPreference: ['lowland', 'deep_crater'],
      },
    ],
    modifiers: {
      stormFrequency: 0.9,
      alienAggression: 0.3,
      solarEfficiency: 0.95,
      initialAlienWave: 0,
    },
    tags: ['Terraformacja', 'Woda', 'Kanion'],
    objectives: [
      'Uruchom zaawansowaną ekstrakcję lodu w kanionie',
      'Podnieś lustro wody do uformowania zbiornika nizinnego',
      'Zasiedl zbocza doliny florą biomasy',
    ],
    icon: '🌊',
    defaultColonyName: 'Marineris Oasis',
  },
];
